### ISSUE TITLE
Defining a local marketplaces.xml

### ISSUE THREAD

**Issue by Mutley5000** [pentaho/marketplace#113]
Hey everyone,

I'm looking to use %UserProfile%/.kettle/marketplaces.xml file to point to a marketplace.xml stored on my companies intranet to test a market_entry (and maybe setup a marketplace within the intranet for our custom plugins as access to outside resources is restricted) as listed here: http://wiki.pentaho.com/display/EAI/Marketplace and in the README.md of: https://github.com/pentaho/marketplace-metadata.  This process works with Pentaho Kettle 5.4 but doesn't seem to work with 6.0+.  

After digging into the release files I found a .cfg file with a variable marketplace.site under Pentaho-installation\data-integration\system\karaf\system\org\pentaho\pentaho-marketplace-di\6.1.0.1-196 and entered the path to my marketplace.xml which didn't work either.

Is it still possible to point to alternative marketplace.xml files?  Is so could someone point out what I'm doing wrong?  Thank you all for your time!

**Comment by pmalves** [comment]
You're doing it right, but you have to wipe out the karaf cache / data dir
so it picks the change

**Comment by Mutley5000** [comment]
Thanks Pedro for the information I'll try that today.

**Comment by Mutley5000** [comment]
Well I'd like to thank you again Pedro!  Clearing out the karaf cache was the key.  Oh and also editing the right .cfg file.  Turns out the one used is pentaho.marketplace.di.cfg under Pentaho-installation\data-integration\system\karaf\etc not the other one I mentioned in my question.  I had a few other non-Pentaho related issues to sort out also but I now have a local marketplace working where internal developers can install our plugins from our local repository.  Just need to tidy up and streamline the process.

Thank you for your time!

**Comment by Mutley5000** [comment]
One more thought, should I make a Wiki or something about this process as any documentation I have read is only relevant for pre Pentaho 6 with the marketplaces.xml file etc?  Just something to help other people till the documentation catches up.
