### ISSUE TITLE
How do you compile and install this ?

### ISSUE THREAD

**Issue by d3vnu11** [pentaho/marketplace#33]
Pretty new here so any help would be great !
--Kev

**Comment by knownasilya** [comment]
Does this still apply to the zips in the release page here on github?

**Comment by matthewtckr** [comment]
Some newer versions use Apache Maven to build.  This can be determined by the presence of a `pom.xml` file in the source artifacts.

**Comment by knownasilya** [comment]
Um, is that the best way to install the marketplace for EE version?

**Comment by matthewtckr** [comment]
If you're looking to build the Marketplace from source, you'd use those zip files.

Most people will use the provided Marketplace plugin, which simply needs to be enabled in a config file.  Pedro Alves [has a blog post about enabling the Marketplace](http://pedroalves-bi.blogspot.com/2015/10/installing-marketpace-in-pentaho-60-ee.html).

Fore more assistance, I'd recommend trying [the Pentaho Forums](http://forums.pentaho.com/forumdisplay.php?73-BI-Platform).

**Comment by knownasilya** [comment]
Thank you for that link! The documentation needs a lot of work...
